#Config including candidate sub-threshold sources (TS >= 16, within 3.5° of KM3NeT neutrino)
#Used to evaluate TS of the sub-threshold sources, make TS map, SED, and light curve

data:
  evfile : events.txt
  scfile : SC.fits

binning:
  roiwidth   : 10.0
  binsz      : 0.1
  binsperdec : 8

selection :
  emin : 1000
  emax : 1000000
  tmin : 697939205.000
  tmax : 765158405.00
  zmax    : 90
  evclass : 128
  evtype  : 3
  filter  : 'DATA_QUAL>0 && LAT_CONFIG==1'
  ra : 94.3
  dec : -7.8
  target : 'KM3-231203A'

gtlike:
  edisp : True
  edisp_bins : -1
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff']

model:
  src_roiwidth : 15.0
  galdiff  : '$CONDA_PREFIX/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits'
  isodiff  : 'iso_P8R3_SOURCE_V3_v1.txt'
  catalogs : 'gll_psc_v35.fit'
  sources  :
    - { name: 'KM3-231203A', ra : 94.3, dec : -7.8, SpectrumType : 'PowerLaw', Index : 2.0, Scale : 1000, Prefactor : !!float 1e-12, SpatialModel: 'PointSource' }
    - { name: 'J0616.1-0428', ra : 94.02298700997044, dec : -4.479466705002961, SpectrumType : 'PowerLaw', Scale : 1000, Prefactor : !!float 1e-12, SpatialModel: 'PointSource' }

components:
  - { selection : { evtype : 4  } } # PSF0
  - { selection : { evtype : 8  } } # PSF1
  - { selection : { evtype : 16 } } # PSF2
  - { selection : { evtype : 32 } } # PSF3

fileio:
   outdir : data
