import numpy as np
import matplotlib.pyplot as plt


font = { 'family': 'Arial', 'weight' : 'normal', 'size'   : 40}
plt.rc('font', **font)
legendfont = {'fontsize' : 36, 'frameon' : False}
plt.rc('legend', **legendfont)
plt.rc('lines', linewidth = 4)
plt.rc('errorbar', capsize = 2)


#Load the light curve generated by 4_lightcurve.py
lc = np.load('data/lc.npy', allow_pickle = True).flat[0]


t_mjd = (lc['tmax_mjd'] + lc['tmin_mjd'])/2
eflux = lc['eflux']
eflux_err = lc['eflux_err']
eflux_ul95 = lc['eflux_ul95']


TS_thresh=4
ts = lc['ts']
measurements=(ts >= TS_thresh)
limits = (ts < TS_thresh)

figure = plt.figure(figsize = (20, 14))
plt.yscale('log')
plt.ylim(1e-7, 1e-4)
plt.xlim(59950, 60800)

#Measurements where TS >= 4
plt.errorbar(t_mjd[measurements], 
             eflux[measurements], 
             fmt = 'o',
             markersize = 12,
             color = 'orangered',
             yerr = eflux_err[measurements])

#Upper limits where TS < 4
plt.errorbar(t_mjd[limits], 
             eflux_ul95[limits], 
             fmt = '_',
             markersize = 30,
             color = 'dimgray',
             yerr = eflux_ul95[limits]/4,
             uplims = True, 
             capsize = 10)

plt.axvline(x = 59988.05332176, color = 'midnightblue', linestyle = 'dashed', linewidth = 4)
plt.xlabel('t [MJD]', fontsize = 40)
plt.ylabel(r'$\phi_{\gamma}$ [MeV cm$^{-2}$ s$^{-1}$]', fontsize = 40)
plt.text(x = 60000.0, y = 4e-5, s = 'KM3230213A', color = 'midnightblue')
plt.text(x = 60500.0, y = 5e-5, s = 'J0616.1-0428', color = 'black', fontsize = 60)
plt.xticks(fontsize = 32)
plt.yticks(fontsize = 32)
plt.grid()
plt.savefig('lightcurve.jpeg')
